### ISSUE TITLE
EPD crashes in action mode whenever a sudden movement is detected

### ISSUE THREAD

**Issue by Promethees** [ros-industrial/easy_perception_deployment#28]
Hi, according to the EMD's pipeline given here: https://easy-manipulation-deployment-docs.readthedocs.io/en/latest/about/overview.html?highlight=pipeline#manipulation-pipeline. I have to feed the grasp_planner with data provided by **/processor/epd_localize_output** topic. Thus, I switch the GUI to **Action** mode.
![Screenshot from 2021-12-20 17-23-35](https://user-images.githubusercontent.com/51523975/146743872-ee6c2c69-5b1d-4e4e-a5e7-264da075c465.png)
As I notice, whenever an object suddenly appeared in the frame or a detected object got sudden movement, the EPD crashed and yielded this error:
![Screenshot from 2021-12-20 17-19-50](https://user-images.githubusercontent.com/51523975/146744060-60c70129-a592-4f5e-b434-a4ba0699c243.png)
This appears to be abnormal as everything worked fine in **visualize** mode regardless of any sudden movement and appearance of objects in the frame. I wonder if there is any solution to improve the systematic reliability? 
By the way, the way we are conducting our experiment is using an external camera (**IntelRealSense**) as an input source instead of using the pre-made rosbag's db in the tutorial.

**Comment by cardboardcode** [comment]
Based on the screenshot you shared, it seems the error reported is as follows:
```bash 
Assertion `allClassNames.size() > *std::max_element(classIndices.begin(), classIndices.end()) failed
```
It seems that, for an unknown reason, the integer **class index** of the object that has the sudden movement exceeds the number of classes defined in your `label_list.txt` file. This can be due to sporadic precision loss. 

While further debugging is done, **please do the following to address the issue in the meantime**:
1. Please comment out [**lines 1109 - 1113** of `p3_ort_base.cpp`](https://github.com/ros-industrial/easy_perception_deployment/blob/518239e380ad3c3e11ba74df53c0d88da8e20718/easy_perception_deployment/include/ort_cpp_lib/p3_ort_base.cpp#L1109-L1113).
```cpp
 // if (!allClassNames.empty()) {
  //  assert(
   //   allClassNames.size() >
    //  *std::max_element(classIndices.begin(), classIndices.end()));
 // }
```

**Comment by cardboardcode** [comment]
Issue is stale. Closing.

@Promethees Please reopen as needed if the issue is still not resolved.
